version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user-registration
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  php:
    image: php:7.4-apache
    volumes:
      - ./php-app:/var/www/html
    ports:
      - 5555:80
    depends_on:
      - mysql
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
